### ISSUE TITLE
Hiding Image

### ISSUE THREAD

**Issue by Mtalha350** [BALKANGraph/OrgChartJS#870]
Hiding Image in Balkan Charts and Form.
I am facing this issue i am not using image but image cannot hide how can resolve it

**Comment by ZornitsaPesheva** [comment]
To remove the image from the node it is enough to remove the image field from **nodebindings**.
Here is how to remove the image fields from the edit/detail form:
```css
.boc-edit-form-avatar {
    display: none !important;
}

.boc-edit-form-header {
    height: 70px !important;
}
```
